In [ ]:
import numpy as np
import pandas as pd

In [ ]:
# Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.
arr = np.array([0, 1, 2, 3, 4, 5])
print(arr.dtype)




int64


In [ ]:
#2. Given a NumPy array 'arr', check if its data type is float64.

arr_float = np.array([1.5, 2.6, 3.7])
is_float64 = arr_float.dtype == np.float64
print("Is arr_float of type float64?", is_float64)


Is arr_float of type float64? True


In [ ]:
# Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.

arr_complex = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)
print("Complex array:", arr_complex)


Complex array: [1.+2.j 3.+4.j 5.+6.j]


In [ ]:
# Convert an existing NumPy array 'arr' of integers to float32 data type

arr_int = np.array([1, 2, 3, 4, 5])
arr_float32 = arr_int.astype(np.float32)
print("Converted to float32:", arr_float32)


Converted to float32: [1. 2. 3. 4. 5.]


In [ ]:
# Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision

arr_float64 = np.array([1.1, 2.2555555557777777777, 3.3], dtype=np.float64)
arr_float32_converted = arr_float64.astype(np.float32)
print("Converted float64 to float32:", arr_float32_converted)


Converted float64 to float32: [1.1       2.2555556 3.3      ]


In [ ]:
# Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.
arr_float = np.array([1.5, 2.6, 3.7])
def array_attributes(arr):
    return arr.shape, arr.size, arr.dtype

attributes = array_attributes(arr_float)
print("Array attributes (shape, size, dtype):", attributes)


Array attributes (shape, size, dtype): ((3,), 3, dtype('float64'))


In [ ]:
# Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.

arr_float = np.array([1.5, 2.6, 3.7])
def array_dimension(arr):
    return arr.ndim

dimension = array_dimension(arr_float)
print("Array dimensionality:", dimension)


Array dimensionality: 1


In [ ]:
# Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.

arr_float = np.array([1.5, 2.6, 3.7])
def item_size_info(arr):
    return arr.itemsize, arr.nbytes

size_info = item_size_info(arr_float)
print("Item size and total size in bytes:", size_info)


Item size and total size in bytes: (8, 24)


In [ ]:
# Create a function array_strides that takes a NumPy array as input and returns the strides of the array

arr_float = np.array([1.5, 2.6, 3.7])
def array_strides(arr):
    return arr.strides

strides = array_strides(arr_float)
print("Array strides:", strides)

Array strides: (8,)


In [ ]:
# Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.

arr_float = np.array([1.5, 2.6, 3.7])
def shape_stride_relationship(arr):
    return arr.shape, arr.strides

shape_stride = shape_stride_relationship(arr_float)
print("Shape and strides:", shape_stride)

Shape and strides: ((3,), (8,))


In [ ]:
#Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements.

def create_zeros_array(n):
    return np.zeros(n)

zeros_array = create_zeros_array(5)
print("Zeros array:", zeros_array)


Zeros array: [0. 0. 0. 0. 0.]


In [ ]:
#Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D NumPy array filled with ones of size `rows x cols`.

def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))

ones_matrix = create_ones_matrix(3, 4)
print("Ones matrix:\n", ones_matrix)


Ones matrix:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified `step`.

def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)

range_array = generate_range_array(0, 10, 2)
print("Range array:", range_array)


Range array: [0 2 4 6 8]


In [ ]:
# Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as arguments and generates a NumPy array with num equally spaced values between `start` and `stop` (inclusive).

def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)

linear_space = generate_linear_space(0, 1, 5)
print("Linear space array:", linear_space)


Linear space array: [0.   0.25 0.5  0.75 1.  ]


In [ ]:
# Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square identity matrix of size `n x n` using `numpy.eye`.

def create_identity_matrix(n):
    return np.eye(n)

identity_matrix = create_identity_matrix(3)
print("Identity matrix:\n", identity_matrix)

Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# Write a function that takes a Python list and converts it into a NumPy array.

def list_to_numpy_array(lst):
    return np.array(lst)

python_list = [1, 2, 3, 4, 5]
numpy_array = list_to_numpy_array(python_list)
print("Converted NumPy array from list:", numpy_array)

Converted NumPy array from list: [1 2 3 4 5]


In [ ]:
# Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data.

original_array = np.array([1, 2, 3, 4, 5])
view_array = original_array.view()
print("Original array:", original_array)
print("View of the original array:", view_array)



Original array: [1 2 3 4 5]
View of the original array: [1 2 3 4 5]


In [ ]:
# Write a function that takes two NumPy arrays and concatenates them along a specified axis.

def concatenate_arrays(arr1, arr2, axis=0):
    return np.concatenate((arr1, arr2), axis=axis)

# Example
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = concatenate_arrays(arr1, arr2)
print("18. Concatenated array:", result)


18. Concatenated array: [1 2 3 4 5 6]


In [ ]:
#Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy. concatenate`.

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5], [6]])
result = np.concatenate((arr1, arr2), axis=1)
print("19. Horizontally concatenated arrays:\n", result)


19. Horizontally concatenated arrays:
 [[1 2 5]
 [3 4 6]]


In [ ]:
#Write a function that vertically stacks multiple NumPy arrays given as a list.

def vertical_stack(arr_list):
    return np.vstack(arr_list)

# Example
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9])
result = vertical_stack([arr1, arr2, arr3])
print("20. Vertically stacked arrays:\n", result)


20. Vertically stacked arrays:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.

def create_range_array(start, stop, step):
    return np.arange(start, stop + 1, step)

# Example
result = create_range_array(0, 10, 2)
print("21. Range array:", result)

21. Range array: [ 0  2  4  6  8 10]


In [ ]:
# Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).

def linspace_array():
    return np.linspace(0, 18, 10)

# Example
result = linspace_array()
print("22. Linspace array:", result)


22. Linspace array: [ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18.]


In [ ]:
# Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).

def logspace_array():
    return np.logspace(0, 3, 5)

# Example
result = logspace_array()
print("23. Logspace array:", result)


23. Logspace array: [   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [ ]:
# Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.

def create_random_dataframe():
    data = np.random.randint(1, 101, size=(5, 3))
    return pd.DataFrame(data, columns=['A', 'B', 'C'])

# Example
df = create_random_dataframe()
print("24. Random DataFrame:\n", df)


24. Random DataFrame:
     A   B   C
0  32  67  62
1  72  89  59
2   8  20   3
3  13  26  23
4   7  40  61


In [ ]:
# Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame.

def replace_negatives(df, column):
    df[column] = df[column].clip(lower=0)
    return df

# Example
df = pd.DataFrame({'A': [1, -2, 3], 'B': [-4, 5, -6]})
result = replace_negatives(df, 'B')
print("25. DataFrame with replaced negatives:\n", result)


25. DataFrame with replaced negatives:
    A  B
0  1  0
1 -2  5
2  3  0


In [ ]:
#Access the 3rd element from the given NumPy array.

arr = np.array([10, 20, 30, 40, 50])
third_element = arr[2]
print("26. Third element:", third_element)


26. Third element: 30


In [ ]:
# Retrieve the element at index (1, 2) from the 2D NumPy array.

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
element = arr_2d[1, 2]
print("27. Element at index (1, 2):", element)


27. Element at index (1, 2): 6


In [ ]:
#Using boolean indexing, extract elements greater than 5 from the given NumPy array

arr = np.array([3, 8, 2, 10, 5, 7])
result = arr[arr > 5]
print("28. Elements greater than 5:", result)

28. Elements greater than 5: [ 8 10  7]


In [ ]:
#Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
result = arr[2:6]
print("29. Sliced array:", result)

29. Sliced array: [3 4 5 6]


In [ ]:
# Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
result = arr_2d[0:2, 1:3]
print("30. Sliced 2D array:\n", result)


30. Sliced 2D array:
 [[2 3]
 [5 6]]


In [ ]:
#Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array

def extract_elements_2d(arr, indices):
    return arr[indices[:, 0], indices[:, 1]]

# Example
arr_31 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
indices_31 = np.array([[0, 1], [1, 2], [2, 0]])
result_31 = extract_elements_2d(arr_31, indices_31)
print("31. Extracted elements:", result_31)


31. Extracted elements: [2 6 7]


In [ ]:
#Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.

def filter_elements(arr, threshold):
    return arr[arr > threshold]

# Example
arr_32 = np.array([1, 5, 3, 8, 2, 7])
result_32 = filter_elements(arr_32, 4)
print("32. Filtered elements:", result_32)

32. Filtered elements: [5 8 7]


In [ ]:
#Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.

def extract_elements_3d(arr, indices_x, indices_y, indices_z):
    return arr[indices_x, indices_y, indices_z]

# Example
arr_33 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
indices_x_33 = np.array([0, 1])
indices_y_33 = np.array([0, 1])
indices_z_33 = np.array([1, 0])
result_33 = extract_elements_3d(arr_33, indices_x_33, indices_y_33, indices_z_33)
print("33. Extracted elements from 3D array:", result_33)


33. Extracted elements from 3D array: [2 7]


In [ ]:
#Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.

def filter_two_conditions(arr, condition1, condition2):
    return arr[(condition1) & (condition2)]

# Example
arr_34 = np.array([1, 5, 3, 8, 2, 7])
result_34 = filter_two_conditions(arr_34, arr_34 > 3, arr_34 < 8)
print("34. Elements satisfying two conditions:", result_34)

34. Elements satisfying two conditions: [5 7]


In [ ]:
#Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.

def extract_elements_2d_separate(arr, row_indices, col_indices):
    return arr[row_indices, col_indices]

# Example
arr_35 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_indices_35 = np.array([0, 2])
col_indices_35 = np.array([1, 2])
result_35 = extract_elements_2d_separate(arr_35, row_indices_35, col_indices_35)
print("35. Extracted elements using separate indices:", result_35)

35. Extracted elements using separate indices: [2 9]


In [ ]:
#Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

arr_36 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
result_36 = arr_36 + 5
print("36. Array after adding 5 to each element:\n", result_36)

36. Array after adding 5 to each element:
 [[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [ ]:
# Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.

arr1_37 = np.array([[1, 2, 3]])
arr2_37 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
result_37 = arr1_37.T * arr2_37
print("37. Result of multiplication:\n", result_37)


37. Result of multiplication:
 [[ 1  2  3  4]
 [10 12 14 16]
 [27 30 33 36]]


In [ ]:
#Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.

arr1_38 = np.array([[1, 2, 3, 4]])
arr2_38 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
result_38 = arr1_38.T + arr2_38
print("38. Result of addition:\n", result_38)

38. Result of addition:
 [[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]


In [ ]:
# Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.

arr1_39 = np.array([[1], [2], [3]])
arr2_39 = np.array([[4, 5, 6]])
result_39 = arr1_39 + arr2_39
print("39. Result of addition:\n", result_39)

39. Result of addition:
 [[5 6 7]
 [6 7 8]
 [7 8 9]]


In [ ]:
#Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility.

arr1_40 = np.array([[1, 2, 3], [4, 5, 6]])
arr2_40 = np.array([[1, 2], [3, 4]])
result_40 = arr1_40[:, :2] * arr2_40
print("40. Result of multiplication:\n", result_40)

40. Result of multiplication:
 [[ 1  4]
 [12 20]]


In [ ]:
# Calculate column wise mean for the given array:

arr_41 = np.array([[1, 2, 3], [4, 5, 6]])
result_41 = np.mean(arr_41, axis=0)
print("41. Column-wise mean:", result_41)

41. Column-wise mean: [2.5 3.5 4.5]


In [ ]:
# Find maximum value in each row of the given array:

arr_42 = np.array([[1, 2, 3], [4, 5, 6]])
result_42 = np.max(arr_42, axis=1)
print("42. Maximum value in each row:", result_42)

42. Maximum value in each row: [3 6]


In [ ]:
# For the given array, find indices of maximum value in each column.

arr_43 = np.array([[1, 2, 3], [4, 5, 6]])
result_43 = np.argmax(arr_43, axis=0)
print("43. Indices of maximum value in each column:", result_43)

43. Indices of maximum value in each column: [1 1 1]


In [ ]:
# For the given array, apply custom function to calculate moving sum along rows.


arr_44 = np.array([[1, 2, 3], [4, 5, 6]])
result_44 = moving_sum(arr_44, 2)
print("44. Moving sum along rows:\n", result_44)


44. Moving sum along rows:
 [[ 3.  5.]
 [ 9. 11.]]


In [ ]:
# In the given array, check if all elements in each column are even.


arr_45 = np.array([[2, 4, 6], [3, 5, 7]])
result_45 = np.all(arr_45 % 2 == 0, axis=0)
print("45. All elements in each column are even:", result_45)

45. All elements in each column are even: [False False False]


In [ ]:
# Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return thereshaped matrix.

def reshape_matrix(arr, m, n):

  if len(arr) != m * n:
    raise ValueError
  return arr.reshape(m, n)

original_array = np.array([1, 2, 3, 4, 5, 6])
reshaped_matrix = reshape_matrix(original_array, 2, 3)
print(reshaped_matrix)


[[1 2 3]
 [4 5 6]]


In [ ]:
# Create a function that takes a matrix as input and returns the flattened array.

def flatten_matrix(matrix):
  return matrix.flatten()
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
flattened_array = flatten_matrix(input_matrix)
print(flattened_array)


[1 2 3 4 5 6]


In [ ]:
# Write a function that concatenates two given arrays along a specified axis.

def concatenate_arrays(array1, array2, axis):
  return np.concatenate((array1, array2), axis=axis)
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
concatenated_array = concatenate_arrays(array1, array2, axis=1)
print(concatenated_array)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
# Create a function that splits an array into multiple sub-arrays along a specified axis.


original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
sub_arrays = split_array(original_array, axis=1, sections=3)
print(sub_arrays)


[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


In [ ]:
# Write a function that inserts and then deletes elements from a given array at specified indices.

def insert_and_delete(array, insert_indices, insert_values, delete_indices):

  array = np.insert(array, insert_indices, insert_values)
  array = np.delete(array, delete_indices)
  return array

original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]
modified_array = insert_and_delete(original_array, indices_to_insert, values_to_insert, indices_to_delete)
print(modified_array)


[ 1 10  4 11  5]


In [ ]:
#Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. Perform element-wise addition between `arr1` and `arr2`.

arr1 = np.random.randint(1, 10, size=10)
arr2 = np.arange(1, 11)
result_add = arr1 + arr2
print(result_add)



[ 6  7  4  6  8 13 14 13 17 12]


In [ ]:
# Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers from 1 to 10. Subtract `arr2` from `arr1` element-wise.

arr1 = np.arange(10, 0, -1)
arr2 = np.arange(1, 11)
result_sub = arr1 - arr2
print(result_sub)

[ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [ ]:
# Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5. Perform element-wise multiplication between `arr1` and `arr2`.

arr1 = np.random.randint(1, 10, size=5)
arr2 = np.arange(1, 6)
result_mul = arr1 * arr2
print(result_mul)

[ 7 10  9 36 30]


In [ ]:
# Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 to 5. Perform element-wise division of `arr1` by `arr2`.

arr1 = np.arange(2, 12, 2)
arr2 = np.arange(1, 6)
result_div = arr1 / arr2
print(result_div)

[2. 2. 2. 2. 2.]


In [ ]:
##Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.

arr1 = np.arange(1, 6)
arr2 = arr1[::-1]
result_exp = arr1 ** arr2
print(result_exp)

[ 1 16 27 16  5]


In [ ]:
#Write a function that counts the occurrences of a specific substring within a NumPy array of strings.

arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
substring = 'hello'
count = count_substring(arr, substring)
print(count)


3


In [ ]:
# Write a function that extracts uppercase characters from a NumPy array of strings.

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

def extract_uppercase_chars(arr):
  return np.array(["".join(char for char in word if char.isupper()) for word in arr])

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
uppercase_chars = extract_uppercase_chars(arr)
print(uppercase_chars)


['H' 'W' 'OAI' 'GPT']


In [ ]:
#Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string

def soln58(arr, old_substr, new_substr):
    return np.char.replace(arr, old_substr, new_substr)

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
print(soln58(arr, 'app', 'zzz'))



['zzzle' 'banana' 'grape' 'pinezzzle']


In [ ]:
# Write a function that concatenates strings in a NumPy array element-wise.

def soln59(arr1, arr2):
    return np.char.add(arr1, arr2)

arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
print(soln59(arr1, arr2))

['HelloOpen' 'WorldAI']


In [ ]:
# Write a function that finds the length of the longest string in a NumPy array. arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

def soln60(arr):
    return np.max(np.char.str_len(arr))

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
print(soln60(arr))

9


In [ ]:
# Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions.

def soln61():
    dataset = np.random.randint(1, 1001, size=100)

    mean = np.mean(dataset)
    median = np.median(dataset)
    variance = np.var(dataset)
    std_dev = np.std(dataset)

    print(f"Mean: {mean}")
    print(f"Median: {median}")
    print(f"Variance: {variance}")
    print(f"Standard Deviation: {std_dev}")

soln61()

Mean: 520.36
Median: 523.0
Variance: 84787.03039999999
Standard Deviation: 291.18212582505816


In [ ]:
# Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.

def soln62():
    dataset = np.random.randint(1, 101, size=50)

    percentiles = np.percentile(dataset, [25, 75])

    print(f"25th Percentile: {percentiles[0]}")
    print(f"75th Percentile: {percentiles[1]}")

soln62()

25th Percentile: 34.25
75th Percentile: 89.5


In [ ]:
# Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's `corrcoef` function.

def soln63(arr1, arr2):
    return np.corrcoef(arr1, arr2)[0, 1]

arr1 = np.random.rand(10)
arr2 = np.random.rand(10)
correlation = soln63(arr1, arr2)
print(f"Correlation Coefficient: {correlation}")

Correlation Coefficient: -0.5228104496186808


In [ ]:
#Create two matrices and perform matrix multiplication using NumPy's `dot` function

def soln64(matrix1, matrix2):
    return np.dot(matrix1, matrix2)
matrix1 = np.random.rand(3, 4)
matrix2 = np.random.rand(4, 2)
result = soln64(matrix1, matrix2)
print(result)

[[1.18215452 0.76093813]
 [0.73193844 0.4758703 ]
 [0.56600904 0.45184648]]


In [ ]:
#Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.

def soln65():

    dataset = np.random.randint(10, 101, size=50)

    percentiles = np.percentile(dataset, [10, 50, 90])
    quartiles = np.percentile(dataset, [25, 75])

    print(f"10th Percentile: {percentiles[0]}")
    print(f"Median (50th Percentile): {percentiles[1]}")
    print(f"90th Percentile: {percentiles[2]}")
    print(f"First Quartile (25th Percentile): {quartiles[0]}")
    print(f"Third Quartile (75th Percentile): {quartiles[1]}")

soln65()

10th Percentile: 18.8
Median (50th Percentile): 54.0
90th Percentile: 90.1
First Quartile (25th Percentile): 36.0
Third Quartile (75th Percentile): 77.5


In [ ]:
# Create a NumPy array of integers and find the index of a specific element.

def soln66(arr, element):
    try:
        return np.where(arr == element)[0][0]
    except IndexError:
        return -1

arr = np.array([1, 5, 8, 12, 15])
print(soln66(arr, 8))  # Output: 2
print(soln66(arr, 20))  # Output: -1

2
-1


In [ ]:
# Generate a random NumPy array and sort it in ascending order.

def soln67(arr):
    return np.sort(arr)

arr = np.random.randint(1, 101, size=10)
print(f"Original array: {arr}")
sorted_arr = soln67(arr)
print(f"Sorted array: {sorted_arr}")

Original array: [16 66 94 16 70  6 75 36 85 28]
Sorted array: [ 6 16 16 28 36 66 70 75 85 94]


In [ ]:
# Filter elements >20  in the given NumPy array.

def soln68(arr):

    return arr[arr > 20]
arr = np.array([12, 25, 6, 42, 8, 30])
filtered_arr = soln68(arr)
print(filtered_arr)

[25 42 30]


In [ ]:
# Filter elements which are divisible by 3 from a given NumPy array.

def soln69(arr):
    return arr[arr % 3 == 0]

arr = np.array([1, 5, 8, 12, 15])
filtered_arr = soln69(arr)
print(filtered_arr)

[12 15]


In [ ]:
# Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array

def soln70(arr):
    return arr[(arr >= 20) & (arr <= 40)]

arr = np.array([10, 20, 30, 40, 50])
filtered_arr = soln70(arr)
print(filtered_arr)

[20 30 40]


In [ ]:
# For the given NumPy array, check its byte order using the `dtype` attribute byteorder.

def soln71(arr):
    return arr.dtype.byteorder

arr = np.array([1, 2, 3])
byte_order = soln71(arr)
print(f"Byte order: {byte_order}")

Byte order: =


In [ ]:
# For the given NumPy array, perform byte swapping in place using `byteswap()`.

def soln72():

    arr = np.array([1, 2, 3], dtype=np.int32)
    print("Original array:", arr)
    arr.byteswap(inplace=True)
    print("Byte-swapped array:", arr)

soln72()



Original array: [1 2 3]
Byte-swapped array: [16777216 33554432 50331648]


In [ ]:
# For the given NumPy array, swap its byte order without modifying the original array using `newbyteorder()`.
def soln73():

    arr = np.array([1, 2, 3], dtype=np.int32)
    print("Original array:", arr)
    swapped_arr = arr.newbyteorder()
    print("Original array after newbyteorder():", arr)
    print("Swapped byte order array:", swapped_arr)

soln73()

Original array: [1 2 3]
Original array after newbyteorder(): [1 2 3]
Swapped byte order array: [16777216 33554432 50331648]


In [ ]:
#  For the given NumPy array and swap its byte order conditionally based on system endianness using`newbyteorder()`.
def soln74():
    arr = np.array([1, 2, 3], dtype=np.int32)
    print("Original array:", arr)
    if np.little_endian:
        swapped_arr = arr.newbyteorder('>')
    else:
        swapped_arr = arr.newbyteorder('<')
    print("Swapped byte order array based on system endianness:", swapped_arr)

soln74()

Original array: [1 2 3]
Swapped byte order array based on system endianness: [16777216 33554432 50331648]


In [ ]:
#  For the given NumPy array, check if byte swapping is necessary for the current system using `dtype`attribute `byteorder`.
def soln75():
    arr = np.array([1, 2, 3], dtype=np.int32)
    print("Original array:", arr)
    if arr.dtype.byteorder == '=':
        print("Byte swapping is not necessary for the current system.")
    else:
        print("Byte swapping is necessary for the current system.")

soln75()

Original array: [1 2 3]
Byte swapping is not necessary for the current system.


In [ ]:
#  Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.
def soln76():

    arr1 = np.arange(1, 11)
    copy_arr = arr1.copy()
    print("Original arr1:", arr1)
    copy_arr[0] = 99
    print("Modified copy_arr:", copy_arr)
    print("arr1 after modifying copy_arr:", arr1)

soln76()

Original arr1: [ 1  2  3  4  5  6  7  8  9 10]
Modified copy_arr: [99  2  3  4  5  6  7  8  9 10]
arr1 after modifying copy_arr: [ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
# Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.

def soln77():

    matrix = np.random.randint(1, 10, size=(3, 3))
    print("Original matrix:\n", matrix)
    view_slice = matrix[1:3, 1:3]
    print("View slice before modification:\n", view_slice)
    view_slice[0, 0] = 99
    print("Modified view slice:\n", view_slice)
    print("Original matrix after modifying view slice:\n", matrix)

soln77()

Original matrix:
 [[3 6 1]
 [5 5 3]
 [7 2 7]]
View slice before modification:
 [[5 3]
 [2 7]]
Modified view slice:
 [[99  3]
 [ 2  7]]
Original matrix after modifying view slice:
 [[ 3  6  1]
 [ 5 99  3]
 [ 7  2  7]]


In [ ]:
# Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.

def soln78():

    array_a = np.arange(1, 13).reshape(4, 3)
    print("Original array_a:\n", array_a)
    view_b = array_a[1:3, 1:3]
    view_b += 5
    print("view_b after broadcasting addition:\n", view_b)
    print("Original array_a after modifying view_b:\n", array_a)

soln78()

Original array_a:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
view_b after broadcasting addition:
 [[10 11]
 [13 14]]
Original array_a after modifying view_b:
 [[ 1  2  3]
 [ 4 10 11]
 [ 7 13 14]
 [10 11 12]]


In [ ]:
# Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view `reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it reflects changes in the original `orig_array`.

def soln79():
    """
    Create a NumPy array `orig_array` of shape (2, 4) and create a reshaped view.
    """
    orig_array = np.arange(1, 9).reshape(2, 4)
    print("Original orig_array:\n", orig_array)
    reshaped_view = orig_array.reshape(4, 2)
    reshaped_view[0, 0] = 99
    print("Modified reshaped_view:\n", reshaped_view)
    print("Original orig_array after modifying reshaped_view:\n", orig_array)

soln79()

Original orig_array:
 [[1 2 3 4]
 [5 6 7 8]]
Modified reshaped_view:
 [[99  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]]
Original orig_array after modifying reshaped_view:
 [[99  2  3  4]
 [ 5  6  7  8]]


In [ ]:
# Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.

def soln80():

    data = np.random.randint(1, 10, size=(3, 4))
    print("Original data:\n", data)
    data_copy = data[data > 5].copy()
    print("data_copy (elements > 5):\n", data_copy)
    if data_copy.size > 0:
        data_copy[0] = 99
    print("Modified data_copy:\n", data_copy)
    print("Original data after modifying data_copy:\n", data)

soln80()

Original data:
 [[3 1 3 3]
 [1 8 3 3]
 [6 6 6 8]]
data_copy (elements > 5):
 [8 6 6 6 8]
Modified data_copy:
 [99  6  6  6  8]
Original data after modifying data_copy:
 [[3 1 3 3]
 [1 8 3 3]
 [6 6 6 8]]


In [ ]:
# Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.

def soln81():

    A = np.array([[1, 2, 3], [4, 5, 6]])
    B = np.array([[7, 8, 9], [10, 11, 12]])
    print("Matrix A:\n", A)
    print("Matrix B:\n", B)
    addition_result = A + B
    subtraction_result = A - B
    print("Addition result:\n", addition_result)
    print("Subtraction result:\n", subtraction_result)

soln81()

Matrix A:
 [[1 2 3]
 [4 5 6]]
Matrix B:
 [[ 7  8  9]
 [10 11 12]]
Addition result:
 [[ 8 10 12]
 [14 16 18]]
Subtraction result:
 [[-6 -6 -6]
 [-6 -6 -6]]


In [ ]:
# Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.

def soln82():

    C = np.random.randint(1, 10, size=(3, 2))
    D = np.random.randint(1, 10, size=(2, 4))
    print("Matrix C:\n", C)
    print("Matrix D:\n", D)
    multiplication_result = np.dot(C, D)
    print("Matrix multiplication result (C * D):\n", multiplication_result)

soln82()

Matrix C:
 [[8 9]
 [8 4]
 [5 1]]
Matrix D:
 [[6 7 5 4]
 [3 9 4 4]]
Matrix multiplication result (C * D):
 [[ 75 137  76  68]
 [ 60  92  56  48]
 [ 33  44  29  24]]


In [ ]:
#  Create a matrix `E` and find its transpose.

def soln83():

    E = np.random.randint(1, 10, size=(3, 4))
    print("Original matrix E:\n", E)
    transpose_E = E.T
    print("Transposed matrix E:\n", transpose_E)

soln83()

Original matrix E:
 [[5 2 1 1]
 [4 2 5 8]
 [6 4 8 7]]
Transposed matrix E:
 [[5 4 6]
 [2 2 4]
 [1 5 8]
 [1 8 7]]


In [ ]:
#  Generate a square matrix `F` and compute its determinant.

def soln84():

    F = np.random.randint(1, 10, size=(3, 3))
    print("Matrix F:\n", F)
    determinant_F = np.linalg.det(F)
    print("Determinant of matrix F:", determinant_F)

soln84()

Matrix F:
 [[2 2 4]
 [7 6 1]
 [6 1 1]]
Determinant of matrix F: -107.99999999999993


In [ ]:
# Create a square matrix `G` and find its inverse.

def soln85():

    G = np.random.randint(1, 10, size=(3, 3))
    print("Matrix G:\n", G)
    try:
        inverse_G = np.linalg.inv(G)
        print("Inverse of matrix G:\n", inverse_G)
    except np.linalg.LinAlgError:
        print("Matrix G is singular and cannot be inverted.")

soln85()

Matrix G:
 [[2 7 9]
 [9 9 2]
 [9 6 1]]
Inverse of matrix G:
 [[ 0.01612903 -0.25268817  0.36021505]
 [-0.0483871   0.42473118 -0.41397849]
 [ 0.14516129 -0.27419355  0.24193548]]
